### ISSUE TITLE
Classic WoW 1.13.5 compatibility 

### ISSUE THREAD

**Issue by GawainXL** [goffauxs/Salad_Cthun#1]
Hey,

Would it be possible to make this compatible with wow classic? @goffauxs 

Thanks in advance

**Comment by mcd8604** [comment]
I'll fork it and see what I can do.

**Comment by goffauxs** [comment]
I've fixed it to work with classic for now. I'd like to redo some of the code as this is quite a dirty way to do it so I might push a new version later mostly for quality of life stuff.
