### ISSUE TITLE
Love the idea! However....

### ISSUE THREAD

**Issue by martijn-veenstra** [goffauxs/Salad_Cthun#2]
.... its doesnt work. /salad doesnt show me anything. Does the /-command register correctly?!

**Comment by martijn-veenstra** [comment]
Message: Interface\AddOns\Salad_Cthun\Salad_Cthun-1.0.lua:190: '=' expected near 'end'
Time: Tue Jul 28 11:00:46 2020
Count: 4
Stack: Interface\AddOns\Salad_Cthun\Salad_Cthun-1.0.lua:190: '=' expected near 'end'

Locals: <none>

**Comment by GawainXL** [comment]
Yeah, when I type /salad, it doesn't recognizes the command @goffauxs

**Comment by goffauxs** [comment]
I must have misstyped something when I edited the code on github. The code should be updated now, however, I suggest downloading the addon from [curseforge](https://www.curseforge.com/wow/addons/salad_cthun) instead as it's much easier to manage.
